config/routes.rb
Moc::Application.routes.draw do  
      
  namespace :api do
    namespace :v1 do
      resources :tokens,:only => [:create, :destroy]
      resources :links,:only => [:create, :destroy]
    end
  end
  
  resources :feeds
  resources :collection
  
  resources :comments do
    resource :childcomments, controller: "child_comments"
  end
  
  resources :links do
    resources :comments
  end
  
  devise_for :users
  
  devise_scope :user do
      get 'login', :to => 'devise/sessions#new'
      delete 'logout', :to => 'devise/sessions#destroy'
      get 'register', :to => 'devise/registrations#new'
    end
  
  
	root :to => 'main#index'
  
  post '/follow/:userName', :to => 'users#follow'
  get '/api/create', :to => 'links#createAPI'
  get '/discuss/:title', :to => 'links#show', :except => ['/add']
  
  delete '/unfollow/:userName', :to =>'users#unfollow'
  
  match '/vote/:id/:updown', :to => "links#updateVote", via: [:get]
  
  match '/change/:id/:method', :to => "links#publicize", via: [:get]
  
  match '/feed', :to => 'feeds#index', via: [:get]
  match '/add/', :to => "links#new", via: [:get]
  match '/add/:url', :to => 'links#new', via: [:get]
  match '/discuss/add', :to => 'links#new', via: [:get]
  match '/:userName' => 'users#show', :except => ['/feed','/follow','/api'], via: [:get]
  match '/comment/add/:id', :to => "child_comments#new", via: [:get]
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  belongs_to :user
  attr_accessible :name, :url ,:user_id
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = User.find_by_username(current_user.username).feeds.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feeds }
    end
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
    @feed = Feed.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feed }
    end
  end

  # GET /feeds/new
  # GET /feeds/new.json
  def new
    @feed = Feed.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feed }
    end
  end

  # GET /feeds/1/edit
  def edit
    @feed = Feed.find(params[:id])
  end

  # POST /feeds
  # POST /feeds.json
  def create
    params[:feed]["owner"] = current_user.username
    
    @feed = Feed.new(params[:feed])

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render json: @feed, status: :created, location: @feed }
      else
        format.html { render action: "new" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feeds/1
  # PUT /feeds/1.json
  def update
    @feed = Feed.find(params[:id])

    respond_to do |format|
      if @feed.update_attributes(params[:feed])
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy

    respond_to do |format|
      format.html { redirect_to feeds_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.haml
= form_for @feed do |f|
  - if @feed.errors.any?
    #error_explanation
      %h2= "#{pluralize(@feed.errors.count, "error")} prohibited this feed from being saved:"
      %ul
        - @feed.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :url
    = f.text_field :url
  .actions
    = f.submit 'Save'

app/views/feeds/edit.html.haml
%h1 Editing feed

= render 'form'

= link_to 'Show', @feed
\|
= link_to 'Back', feeds_path

app/views/feeds/index.html.haml
.left-bar
	%ul
		%header
			= link_to("/") do
				%span.item.title= "Moc"
		- if user_signed_in?
			%li
				= link_to("links") do
					%span.item= "Links"
			%li
				= link_to("feed") do
					%span.item= "Feeds"
			
			%li
				%a{:href => current_user.username}
					%span.item= "Profile"
					
			%li
				=link_to("logout", :method => "delete") do
					%span.item= "Logout"
				
		- else
			%li
				%a{:href => "login"}
					%span.item= "Login"
		
			%li
				%a{:href => "register"}
					%span.item= "Register"

.container
	- @feeds.each do |feed|
		%section
			%header
				%h1.linkTitle= feed.title
				=link_to (feed.url) do
					%span.url= feed.url
			%article
				%p=feed.content

app/views/feeds/new.html.haml
%h1 New feed

= render 'form'

= link_to 'Back', feeds_path

app/views/feeds/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @feed.name
%p
  %b Url:
  = @feed.url

= link_to 'Edit', edit_feed_path(@feed)
\|
= link_to 'Back', feeds_path