config/routes.rb
Moc::Application.routes.draw do  
      
  namespace :api do
    namespace :v1 do
      resources :tokens,:only => [:create, :destroy]
      resources :links,:only => [:create, :destroy]
    end
  end
  
  resources :feeds
  resources :collection
  
  resources :comments do
    resource :childcomments, controller: "child_comments"
  end
  
  resources :links do
    resources :comments
  end
  
  devise_for :users
  
  devise_scope :user do
      get 'login', :to => 'devise/sessions#new'
      delete 'logout', :to => 'devise/sessions#destroy'
      get 'register', :to => 'devise/registrations#new'
    end
  
  
	root :to => 'main#index'
  
  post '/follow/:userName', :to => 'users#follow'
  get '/api/create', :to => 'links#createAPI'
  get '/discuss/:title', :to => 'links#show', :except => ['/add']
  
  delete '/unfollow/:userName', :to =>'users#unfollow'
  
  match '/vote/:id/:updown', :to => "links#updateVote", via: [:get]
  
  match '/change/:id/:method', :to => "links#publicize", via: [:get]
  
  match '/feed', :to => 'feeds#index', via: [:get]
  match '/add/', :to => "links#new", via: [:get]
  match '/add/:url', :to => 'links#new', via: [:get]
  match '/discuss/add', :to => 'links#new', via: [:get]
  match '/:userName' => 'users#show', :except => ['/feed','/follow','/api'], via: [:get]
  match '/comment/add/:id', :to => "child_comments#new", via: [:get]
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  
  attr_accessible :content, :user_id, :title, :url, :vote, :private
  
  paginates_per 20
  
  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT following_id FROM relationships
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id", 
          user_id: user.id)
  end
end

app/controllers/links_controller.rb
#encoding: UTF-8

require 'open-uri'
require 'cgi'
require 'json'

class LinksController < ApplicationController
  # GET /links
  # GET /links.json
  def index
    @links = User.find_by_username(current_user.username).links

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @links }
    end
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @link = Link.find_by_title(params[:title])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/new
  # GET /links/new.json
  def new
    @link = Link.new
    
    if params[:url] != nil
      @title = Link.find(params[:url]).title
      @url = Link.find(params[:url]).url
    end
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/1/edit
  def edit
    @link = Link.find(params[:id])
  end

  # POST /links
  # POST /links.json
  def create
    params[:link]["user_id"] = current_user.id
    params[:link]["vote"] = 0
    
    @link = Link.new(params[:link])

    respond_to do |format|
      if @link.save
        format.html { redirect_to "/" , notice: 'Link was successfully created.' }
        format.json { render json: @link, status: :created, location: @link }
      else
        format.html { render action: "new" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def createAPI
    @user = User.find_by_authentication_token(params[:auth_token])
    
    url = params[:url]
    title = params[:title]
    
    if title.include? "."
      title = title.gsub!(".","")
    end
    
    if title.include? ","
      title = title.gsub!(",","")
    end
    
    if title.include? "'"
      title = title.gsub!("'","")
    end    
    
    params = ActionController::Parameters.new({
      link: {
        user_id:@user.id,
        vote: 0,
        content: "",
        url: url,
        title:title,
        private: false
      }
    })
    
    params[:link]["user_id"] = @user.id
    
    @link = Link.new(params[:link])
    
    if @link.save
      render :status=>200, :json=>{status: :created}
    end
  end
  
  def publicize
    @link = Link.find(params[:id])
    if User.find_by_username(@link.user.username).id == current_user.id	
      if params[:method] == "public"
        @link.private = false
      else
        @link.private = true
      end
    
      @link.save
    
      redirect_to "/discuss/" + @link.title
    end
  end
  
  def updateVote
    @link = Link.find(params[:id])
    if params[:updown] == "up"
      @link.vote = @link.vote + 1
      puts @link.vote
    else
      @link.vote = @link.vote - 1
    end    
    @link.save
    
    redirect_to URI::encode("/discuss/" + @link.title)
  end
  
  # PUT /links/1
  # PUT /links/1.json
  def update
    @link = Link.find(params[:id])

    respond_to do |format|
      if @link.update_attributes(params[:link])
        format.html { redirect_to @link.title, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link = Link.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end  
end

app/helpers/links_helper.rb
module LinksHelper
  def isPrivate(link)
    if link.private == true
      true
    else
      false
    end
  end
end

app/views/links/_form.html.haml
= form_for @link do |f|
	%header
		%h3
			= f.text_field :title, :value => @title, :placeholder => "Title", :class => "titlefield"
			= f.text_field :url, :value => @url, :placeholder => "URL", :class => "urlfield"
	
	.content
		= f.text_area :content, :rows => 3, :placeholder => "Content", :class => "contentfield"
		= f.label "Is Private?"
		= f.check_box :private
	.actions
		= f.submit 'Publish', :class => "button"

app/views/links/edit.html.haml
%h1 Editing link

= render 'form'

= link_to 'Show', @link
\|
= link_to 'Back', links_path

app/views/links/index.html.haml
.left-bar
	%ul
		%header
			= link_to("/") do
				%span.item.title= "Moc"
		- if user_signed_in?
			%li
				= link_to("links") do
					%span.item= "Links"
								
			%li
				%a{:href => current_user.username}
					%span.item= "Profile"
					
			%li
				=link_to("logout", :method => "delete") do
					%span.item= "Logout"
					
			%li
				=link_to("add") do
					%span.add-button.item= "New link"
				
		- else
			%li
				%a{:href => "login"}
					%span.item= "Login"
		
			%li
				%a{:href => "register"}
					%span.item= "Register"

.container
	%ul
		- @links.each do |link|
			%li.feed
				=link_to link.url do
					%span.linkTitle= link.title
				- if isPrivate(link)
					%i.icon-lock
				=link_to "/discuss/" + link.title do
					%i.icon-link
				=link_to "/vote/" + link.id.to_s + "/up" do
					%i.icon-thumbs-up.right
				=link_to "/add/" + link.id.to_s do
					%i.icon-bookmark.right
				- if isPrivate(link)
					=link_to("/change/" + link.id.to_s + "/public") do
						%i.icon-unlock-alt.right
				- else
					=link_to("/change/" + link.id.to_s + "/private") do
						%i.icon-lock.right

app/views/links/new.html.haml
.left-bar
	%ul
		%header
			= link_to("/") do
				%span.item.title= "Moc"
		- if user_signed_in?
			%li
				= link_to("links") do
					%span.item= "Links"
			
			%li
				%a{:href => current_user.username}
					%span.item= "Profile"
					
			%li
				=link_to("logout", :method => "delete") do
					%span.item= "Logout"
					
			%li
				=link_to("add") do
					%span.add-button.item= "New link"
				
		- else
			%li
				%a{:href => "login"}
					%span.item= "Login"
		
			%li
				%a{:href => "register"}
					%span.item= "Register"

.container
	%article.write
		=render 'form'

app/views/links/show.html.haml
.left-bar
	%ul
		%header
			= link_to("/") do
				%span.item.title= "Moc"
		- if user_signed_in?
			%li
				= link_to("links") do
					%span.item= "Links"
			
			%li
				%a{:href => current_user.username}
					%span.item= "Profile"
					
			%li
				=link_to("logout", :method => "delete") do
					%span.item= "Logout"
					
			%li
				=link_to("add") do
					%span.add-button.item= "New link"
				
		- else
			%li
				%a{:href => "login"}
					%span.item= "Login"
		
			%li
				%a{:href => "register"}
					%span.item= "Register"

.container
	%section
		%article
			=link_to @link.url do
				%h1.title= @link.title
			- if isPrivate(@link)
				%i.icon-lock
			%span.item= "by " + @link.user.username + " — "
						
			=link_to("/add/" + @link.id.to_s) do
				%span Read it later
			- if User.find_by_username(@link.user.username).id == current_user.id	
				%span —	
				- if isPrivate(@link)
					=link_to("/change/" + @link.id.to_s + "/public") do
						%span Publicize
				- else
					=link_to("/change/" + @link.id.to_s + "/private") do
						%span Make private
									
			.content
				%span.item.content= @link.content
				
				- if User.find_by_username(@link.user.username).id == current_user.id
					=link_to @link, {:confirm => 'Are you sure?', :method => :delete} do
						%span.item.delete= "Delete"
				
				
				.vote
					=link_to "/vote/" + @link.id.to_s + "/up" do
						.button= "Recommand"
					
		
		.comments#comment
			%h1.title Comments
			=render @link.comments
			=render "comments/form"